shop/main_app/urls.py
from django.contrib.flatpages import views
from django.urls import path

from .views import MainPageView, PromotionView

urlpatterns = [
    path('', MainPageView.as_view(), name='index'),
    path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    path('contact/', views.flatpage, {'url': '/contact/'}, name='contact'),
    path('payments/', views.flatpage, {'url': '/payments/'}, name='payments'),
    path('delivery/', views.flatpage, {'url': '/delivery/'}, name='delivery'),
    path('faqs/', views.flatpage, {'url': '/faqs/'}, name='faqs'),
    path('support/', views.flatpage, {'url': '/support/'}, name='support'),
    path('privacy/', views.flatpage, {'url': '/privacy/'}, name='privacy'),
    path('warranty/', views.flatpage, {'url': '/warranty/'}, name='warranty'),
    path('conditions/', views.flatpage, {'url': '/conditions/'},
         name='conditions'),
    path('return/', views.flatpage, {'url': '/return/'}, name='return'),
    path('intellproperty/', views.flatpage, {'url': '/intellproperty/'},
         name='intellproperty'),
    path('promo/<str:slug_promo>/', PromotionView.as_view(), name='promo'),
]

shop/orders/urls.py
from django.urls import path

from .views import Basket, cart_add, cart_remove, OrderCreate, OrderCreated

app_name = 'orders'

urlpatterns = [
    path('', Basket.as_view(), name='orders_index'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('add_order/', OrderCreate.as_view(), name='order_add'),
    path('order_created/<int:pk>/', OrderCreated.as_view(),
         name='order_created'),
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('shopping/', include('shopping.urls')),
    path('shopping/orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/main_app/models.py
from django.core import validators
from django.db import models
from django.urls import reverse

from autoslug import AutoSlugField
from uuslug import uuslug

from shopping.models import BrandNameDB, CategoryDB


def instance_slug(instance):
    return instance.title


def slugify_value(value):
    return value.replace(' ', '-')


class PromotionDB(models.Model):
    """
    Model PromotionDB to save new promotions to database
    """

    promo_title = models.CharField(
            max_length=30,
            verbose_name='Название акции'
    )
    is_active = models.BooleanField(
            default=False,
            verbose_name='Активна'
    )
    category = models.ManyToManyField(
            CategoryDB,
            related_name='from_category',
            blank=True,
            verbose_name='Категория'
    )
    brand = models.ManyToManyField(
            BrandNameDB,
            related_name='from_brand',
            blank=True,
            verbose_name='Производитель'
    )
    discount = models.DecimalField(
            max_digits=3,
            decimal_places=2,
            verbose_name='Скидка',
            null=True,
            help_text='От 0.01 до 0.99',
            validators=[
                validators.MinValueValidator(0.01),
                validators.MaxValueValidator(0.99)
            ]
    )
    description = models.TextField(
            blank=True,
            verbose_name='Описание акции'
    )
    photo = models.ImageField(
            upload_to='photo/promo/%Y/%m/%d',
            verbose_name='Фото',
            null=True
    )
    slug = AutoSlugField(
            max_length=35,
            db_index=True,
            unique=True,
            verbose_name='URL Акции',
            populate_from=instance_slug,
            slugify=slugify_value
    )

    def save(self, *args, **kwargs):
        self.slug = uuslug(self.promo_title, instance=self)
        super(PromotionDB, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('promo', kwargs={'slug_promo': self.slug})

    def __str__(self):
        return f'{self.promo_title}'

    def get_category(self):
        return ','.join([str(category) for category in self.category.all()])

    def get_brand(self):
        return ','.join([str(brand) for brand in self.brand.all()])

    class Meta:
        verbose_name = 'Акция(ю)'
        verbose_name_plural = 'Акции(ий)'
        ordering = ('-is_active',)

shop/main_app/forms.py
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError

from .models import PromotionDB


class PromotionForm(forms.ModelForm):
    """
    Form for validating model fields
    """

    class Meta:
        model = PromotionDB
        fields = ('promo_title', 'is_active', 'discount',
                  'category', 'brand', 'photo',)

    def clean(self):
        super().clean()
        errors = {}
        category = self.cleaned_data.get('category')
        brand = self.cleaned_data.get('brand')

        if not category and not brand:
            errors[NON_FIELD_ERRORS] = ValidationError(
                    'В акции должна быть указана хотя бы одна '
                    'категория и/или один производитель'
            )
        if errors:
            raise ValidationError(errors)

shop/main_app/views.py
from django.db.models import Q
from django.views.generic import TemplateView

from main_app.models import PromotionDB
from orders.cart import Cart
from shopping.models import GoodsDB
from shopping.views import ShowAllGoods


class MainPageView(TemplateView):
    """
    Class to display the main page
    """

    model = GoodsDB
    template_name = 'main_app/index.html'


# todo search get q
class SearchGoodView(ShowAllGoods):
    """doc string"""

    def get_queryset(self):
        search = self.request.GET.get('q')
        return GoodsDB.objects.filter(presence=True, title__icontains=search)


class CartShowView(TemplateView):
    """
    Class to display the cart
    """

    template_name = 'inc/_cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Cart(self.request)
        context['cart'] = cart
        return context


class PromotionView(ShowAllGoods):
    """
    Class to display promotion goods
    """

    model = GoodsDB

    def get_queryset(self):
        queryset = super().get_queryset()
        active_promo = PromotionDB.objects.filter(
                slug=self.kwargs.get('slug_promo')
        )
        for promo in active_promo:
            goods = Q(category__in=[cat.id for cat in promo.category.all()]) \
                    | Q(brand__in=[brand.id for brand in promo.brand.all()])
            queryset = GoodsDB.objects.filter(presence=True).filter(goods)
        if self.request.GET.get('sort_on'):
            queryset = self.get_queryset_by_sort(queryset)
        return queryset

shop/main_app/templates/inc/_cart.html
{% load static %}

<div class="dropdown cart-dropdown pl-1 text-dark">
    <a href="{% url 'orders:orders_index' %}" class="dropdown-toggle" role="button" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false" data-display="static"><i class="icon-shopping-cart"></i></a>

    <span class="cart-count badge-circle">{{ cart | length }}</span>

    <div class="dropdown-menu">
        <div class="dropdownmenu-wrapper">
            <div class="dropdown-cart-header">

                <span>{{ cart | length }} товаров</span>

                <a href="{% url 'orders:orders_index' %}" class="float-right">В корзине</a>
            </div>

            {% for item in cart %}
            {% with good=item.product %}

            <div class="dropdown-cart-products">
                <div class="product">
                    <div class="product-details">
                        <h4 class="product-title">
                            <a href="{{ good.get_absolute_url }}">{{ good }}</a>
                        </h4>
                        <span class="cart-product-info"><span class="cart-product-qty">
                            {{ item.quantity }} х {{ item.price }} руб.
                        </span></span>
                    </div>

                    <figure class="product-image-container">

                        {% if good.images_for_goods.all %}
                        {% for photo in good.images_for_goods.all %}
                        {% if forloop.counter == 1 %}

                        <a href="{{ good.get_absolute_url }}">
                            <img src="{{ photo.photo.url }}" width="150">
                        </a>

                        {% endif %}
                        {% endfor %}

                        {% else %}

                        <a href="{{ good.get_absolute_url }}">
                            <img src="{% static 'assets/images/photo_net.jpg' %}" width="150">
                        </a>

                        {% endif %}

                        <a href="{% url 'orders:cart_remove' good.id %}" class="btn-remove icon-cancel"
                           title="Удалить из корзины"></a>

                    </figure>
                </div>
            </div>

            {% endwith %}
            {% endfor %}

            <div class="dropdown-cart-total">
                <span>Всего</span><span class="cart-total-price float-right">{{ cart.get_total_price }} руб.</span>
            </div>

            <div class="dropdown-cart-action">
                <a href="{% url 'orders:orders_index' %}" class="btn btn-dark btn-block">Перейти в корзину</a>

            </div>
        </div>
    </div>
</div>

shop/main_app/templates/inc/_fav_goods.html
{% load static %}

<section class="section-2 product-collection container">
    <div class="row m-0">

        {% for good in goods %}

        <div class="col-md-4 col-6 appear-animate" data-animation-name="fadeInRightShorter"
             data-animation-delay="400">
            <div class="product-default inner-quickview inner-icon">

                {% for key, value in goods_dict.items %}
                {% if good == value.product %}

                <figure>

                    {% if good.images_for_goods.all %}
                    {% for photo in good.images_for_goods.all %}
                    {% if forloop.counter == 1 %}

                    <a href="{{ good.get_absolute_url }}">
                        <img src="{{ photo.photo.url }}" alt="product" width="400" height="400">
                    </a>

                    {% endif %}
                    {% endfor %}

                    {% else %}

                    <a href="{{ good.get_absolute_url }}">
                        <img src="{% static 'assets/images/photo_net.jpg' %}">
                    </a>

                    {% endif %}

                    {% if value.promo %}

                    <div class="label-group">
                        <span class="product-label label-sale">-{{ value.promo }}%</span>
                    </div>

                    {% endif %}

                </figure>

                <div class="product-details">
                    <div class="category-wrap">
                        <div class="category-list">
                            <a href="{{ good.category.get_absolute_url }}" class="product-category">
                                Категория: {{ good.category }}
                            </a>
                        </div>
                    </div>

                    <h2 class="product-title">
                        <a href="{{ good.get_absolute_url }}">{{ good }}</a>
                    </h2>

                    <div class="ratings-container">
                        <div class="product-ratings">
                            <span class="ratings" style="width:{{ value.rating }}%"></span>
                            <span class="tooltiptext tooltip-top"></span>
                        </div>
                    </div>

                    <div class="price-box">

                        {% if value.promo %}

                        <span class="old-price">{{ good.price }} руб.</span>
                        <span class="product-price">{{ value.new_price }} руб.</span>

                        {% else %}

                        <span class="product-price">{{ good.price }} руб.</span>

                        {% endif %}
                    </div>
                </div>
            </div>

            {% endif %}
            {% endfor %}

        </div>

        {% endfor %}

    </div>
</section>

shop/main_app/templates/inc/_index.html
{% load static %}

<section class="section-2 product-collection container">
    <div class="row m-0">

        {% for good in goods %}

        <div class="col-md-4 col-6 appear-animate" data-animation-name="fadeInRightShorter"
             data-animation-delay="400">
            <div class="product-default inner-quickview inner-icon">

                {% for key, value in show_photo.items %}
                {% if key == good %}

                <figure>

                    {% if value %}

                    <a href="{{ key.get_absolute_url }}">
                        <img src="{{ value.photo.url }}" alt="product" width="400" height="400"/></a>

                    {% else %}

                    <a href="{{ key.get_absolute_url }}">
                        <img src="https://picsum.photos/1024/768?grayscale"></a>

                    {# добавить в корзину? #}
                    <div class="btn-icon-group">
                        <button class="btn-icon btn-add-cart" data-toggle="modal" data-target="#addCartModal"><i
                                class="icon-bag"></i></button>
                    </div>

                    {% endif %}

                </figure>

                {% endif %}
                {% endfor %}

                <div class="product-details">
                    <div class="category-wrap">
                        <div class="category-list">
                            <a href="{{ good.category.get_absolute_url }}" class="product-category">{{ good.category }}</a>
                        </div>
                    </div>

                    <h2 class="product-title">
                        <a href="{{ good.get_absolute_url }}">{{ good.title }}</a>
                    </h2>

                    <div class="ratings-container">
                        <div class="product-ratings">

                            {% for key, value in show_rating.items %}
                            {% if key == good %}

                            <span class="ratings" style="width:{{ value }}%"></span><!-- End .ratings -->
                            <span class="tooltiptext tooltip-top"></span>

                            {% endif %}
                            {% endfor %}

                        </div>
                    </div>


                    <div class="price-box">

                        {% for key, value in show_new_price.items %}
                        {% if key == good %}

                        <span class="old-price">{{ key.price }} y.e.</span>
                        <span class="product-price">{{ value }} y.e.</span>

                        {% endif %}
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</section>

shop/main_app/templates/inc/_promo.html
{% load static %}
{% load index_filters %}

<section class="section-1 pt-0">
    <div class="home-slider slide-animate owl-carousel owl-theme show-nav-hover">

        {% for promo in promotions %}

        <div class="home-banner bg-img banner-left" style="background-image: url( {{ promo.photo.url }} );">
            <div class="container position-relative">
                <div class="banner-layer banner-layer-middle">
                    <h2 class="m-b-1 appear-animate banner-title" data-animation-duration="1200"
                        data-animation-delay="800" data-animation-name="fadeIn">{{ promo.promo_title }}</h2>

                    <h3 class="text-uppercase rotated-upto-text mb-0 position-relative appear-animate"
                        data-animation-delay="800" data-animation-duration="1200" data-animation-name="blurIn">
                        <small>OFF</small>{{ promo.discount|discount }}%</h3>

                    <hr class="divider-short-thick appear-animate" data-animation-duration="1200"
                        data-animation-delay="800" data-animation-name="fadeIn">

                    {% for key, value in cat_promo.items %}
                    {% if key == promo %}
                    {% for cat in value %}

                    <h5 class="text-uppercase d-inline-block mb-0 ls-n-20 pr-1 pt-2 appear-animate"
                        data-animation-delay="1600" data-animation-duration="1200"
                        data-animation-name="fadeIn">{{ cat }}</h5>

                    {% endfor %}
                    {% endif %}
                    {% endfor %}

                    <br>

                    {% for key, value in brand_promo.items %}
                    {% if key == promo %}
                    {% for brand in value %}

                    <h5 class="text-uppercase d-inline-block mb-0 ls-n-20 pr-1 pt-2 appear-animate"
                        data-animation-delay="1600" data-animation-duration="1200"
                        data-animation-name="fadeIn">{{ brand }}</h5>

                    {% endfor %}
                    {% endif %}
                    {% endfor %}

                    <br>

                    <a href="{{ promo.get_absolute_url }}" class="btn btn-dark btn-xl btn-icon-right appear-animate"
                       role="button" data-animation-delay="2200" data-animation-duration="1200"
                       data-animation-name="fadeIn">КУПИ СЕЙЧАС <i class="fas fa-long-arrow-alt-right"></i></a>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</section>

shop/main_app/templates/inc/_submenu.html
{% load static %}
{% load static mptt_tags %}

<div class="col-lg-6">
    <div class="menu-title mb-1">
        <a href="{% url 'shopping' %}">Категории</a>
    </div>

    <div class="widget-body">

        {% recursetree categories %}

        <ul class="submenu">
            <li>
                {% if node.level == 0 %}
                <strong>{{ node.title }}</strong>

                    {% for item in categories %}
                    {% if item.parent_id == node.id %}

                    <ul class="submenu">
                            <a href="{{ item.get_absolute_url }}">{{ item.title }}</a>
                    </ul>

                    {% endif %}
                    {% endfor %}

                {% endif %}

                {% if not node.is_leaf_node %}
                <ul class="submenu">
                    {{ children }}
                </ul>
                {% endif %}

            </li>
        </ul>

        {% endrecursetree %}

    </div>
</div>

<div class="col-lg-6">
    <div class="menu-title mb-1">
        <a href="{% url 'shopping' %}">Бренды</a>
    </div>

    <ul class="submenu">
        {% for brand in brands %}

        <li><a href="{{ brand.get_absolute_url }}"><strong>{{ brand.title }}</strong></a></li>

        {% endfor %}
    </ul>

</div>