shop/orders/urls.py
from django.urls import path

from .views import Basket, cart_add, cart_remove, OrderCreate, OrderCreated

app_name = 'orders'

urlpatterns = [
    path('', Basket.as_view(), name='orders_index'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('add_order/', OrderCreate.as_view(), name='order_add'),
    path('order_created/<int:pk>/', OrderCreated.as_view(),
         name='order_created'),
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('shopping/', include('shopping.urls')),
    path('shopping/orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/orders/models.py
from django.db import models
from django.urls import reverse

from phonenumber_field.modelfields import PhoneNumberField

from accounts.models import ShopUser
from shopping.models import GoodsDB


class OrderDB(models.Model):
    """
    Model OrderDB to save the details of new orders to database
    """

    ACCEPTED = 'NR'
    SENT = 'SE'
    STATUS_CHOICES = (
        (ACCEPTED, 'На рассмотрении'),
        (SENT, 'Отправлен'),
    )

    POST_RUSSIA = 'PR'
    COURIER_DELIVERY = 'CD'
    EXPRESS_COURIER_DELIVERY = 'ED'
    DELIVERY_CHOICES = (
        (POST_RUSSIA, 'Получите Ваш заказ в отделении Почты России'),
        (COURIER_DELIVERY, 'Заберите Ваш заказ в офисе курьерской службы'),
        (EXPRESS_COURIER_DELIVERY, 'Ваш товар доставят Вам домой курьером'),
    )

    for_user = models.ForeignKey(
            ShopUser,
            on_delete=models.CASCADE,
            null=True,
            related_name='order_user_name',
            verbose_name='Покупатель'
    )
    postal_code = models.PositiveBigIntegerField(
        verbose_name='Почтовый индекс'
    )
    country = models.CharField(
            default='Российская Федерация',
            max_length=100,
            verbose_name='Страна'
    )
    region = models.CharField(
            max_length=100,
            default='Хабаровский край',
            verbose_name='Регион'
    )
    city = models.CharField(
            max_length=100,
            default='Хабаровск',
            verbose_name='Населенный пункт'
    )
    address = models.CharField(
            max_length=150,
            verbose_name='Адрес'
    )
    phone_number = PhoneNumberField(
            verbose_name='Номер телефона'
    )
    status = models.CharField(
            max_length=2,
            choices=STATUS_CHOICES,
            default=ACCEPTED,
            verbose_name='Статус заказа'
    )
    date_at = models.DateTimeField(
            auto_now_add=True,
            verbose_name='Дата создания записи'
    )
    date_up = models.DateTimeField(
            auto_now=True,
            verbose_name='Дата последнего изменения записи'
    )
    delivery_type = models.CharField(
            max_length=2,
            choices=DELIVERY_CHOICES,
            default=POST_RUSSIA,
            verbose_name='Выберите тип доставки'
    )

    def __str__(self):
        return f'Запись покупки № {self.id}'

    def get_total_price(self):
        """
        The function to return the total order cost
        """

        return sum(item.get_cost() for item in self.items.all())

    def get_absolute_url(self):
        return reverse('orders:order_created', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('-date_up',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы(ов)'


class OrderItemDB(models.Model):
    """
    Model OrderItemDB to save of order's lists to database
    """

    order = models.ForeignKey(
            OrderDB,
            on_delete=models.PROTECT,
            related_name='items',
            verbose_name='Заказ'
    )
    product = models.ForeignKey(
            GoodsDB,
            on_delete=models.PROTECT,
            related_name='order_items',
            verbose_name='Товар'
    )
    price = models.DecimalField(
            max_digits=10,
            decimal_places=2,
            verbose_name='Цена при покупке'
    )
    quantity = models.PositiveIntegerField(
            default=1,
            verbose_name='Количество'
    )

    def __str__(self):
        return f'{self.id}'

    def get_cost(self):
        """
        The function to return the total position cost
        """

        return self.price * self.quantity

    class Meta:
        ordering = ('-order',)
        verbose_name = 'Товар(а)'
        verbose_name_plural = 'Товары(ов)'

shop/orders/forms.py
from django import forms

from .models import OrderDB

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    """
    Form to add the to the basket
    """

    quantity = forms.TypedChoiceField(
            label='Количество',
            choices=PRODUCT_QUANTITY_CHOICES,
            coerce=int,  # идет автоматическое преобразование в целое число
    )
    update = forms.BooleanField(
            required=False,
            initial=False,
            widget=forms.HiddenInput
    )


class OrderCreateForm(forms.ModelForm):
    """
    Form for creating an order record in the model OrderDB
    """

    class Meta:
        model = OrderDB
        fields = ('postal_code', 'country', 'region', 'city', 'address',
                  'phone_number', 'delivery_type',)

shop/orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F, Prefetch
from django.shortcuts import redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import DetailView, CreateView, TemplateView

from .cart import Cart
from .forms import CartAddProductForm, OrderCreateForm
from .models import OrderDB, OrderItemDB
from .tasks import send_admin_mail
from shopping.models import GalleryDB, GoodsDB


@require_POST
def cart_add(request, product_id):
    """
    The processing function to add the good to the basket
    """

    cart = Cart(request)
    product = get_object_or_404(GoodsDB, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(good=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])

    if 'next' in request.GET:
        return redirect(request.GET['next'])
    else:
        return redirect('orders:orders_index')


def cart_remove(request, product_id):
    """
    The processing function to remove the good from the basket
    """

    cart = Cart(request)
    product = get_object_or_404(GoodsDB, id=product_id)
    cart.remove(product)
    return redirect('orders:orders_index')


class Basket(TemplateView):
    """
    Class to display the basket contents for the given session
    """

    template_name = 'orders/basket.html'

    def get_context_data(self, **kwargs):
        context = super(Basket, self).get_context_data(**kwargs)
        cart = Cart(self.request)
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                initial={'quantity': item['quantity'],'update': True}
            )
        context['cart'] = cart
        return context


class OrderCreate(LoginRequiredMixin, CreateView):
    """
    Class to create an order record in the model OrderDB
    """

    template_name = 'orders/order.html'
    form_class = OrderCreateForm
    raise_exception = True

    def form_valid(self, form):
        cart = Cart(self.request)

        if len(cart) > 0:
            form.instance.for_user = self.request.user
            order = form.save()
            send_admin_mail.delay(order.id, order.for_user.id)

            for item in cart:
                OrderItemDB.objects.create(
                        order=order,
                        product=item['product'],
                        price=item['price'],
                        quantity=item['quantity']
                )
                views = item['product']
                views.n_views = F('n_views') + 1
                views.save()

            cart.clear()
            return super(OrderCreate, self).form_valid(form)
        else:
            return super(OrderCreate, self).form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super(OrderCreate, self).get_context_data(**kwargs)
        return context


class OrderCreated(LoginRequiredMixin, DetailView):
    """
    Class to display the created order information
    """

    model = OrderDB
    template_name = 'orders/order_created.html'
    context_object_name = 'order'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_items'] = OrderItemDB.objects.filter(
                order__pk=self.kwargs.get('pk'))\
            .select_related('order', 'product')\
            .prefetch_related(Prefetch('product__images_for_goods',
                                       queryset=GalleryDB.objects.all()))
        return context

    def get_queryset(self):
        queryset = OrderDB.objects.filter(pk=self.kwargs.get('pk'))
        return queryset

shop/orders/templates/orders/basket.html
{% extends 'base.html' %}}
{% load static %}
{% load bootstrap4 %}


{% block title %}

Корзина  :: {{ block.super }}

{% endblock %}

{% block content %}

<div class="page-wrapper">
    <main class="main">

        <nav aria-label="breadcrumb" class="breadcrumb-nav">
            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}"><i class="icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="{% url 'shopping' %}">Магазин</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Корзина</li>
                </ol>
            </div>
        </nav>

        <div class="container mb-6">
            <div class="row">
                <div class="col-lg-8">
                    <div class="cart-table-container">
                        <table class="table table-cart">

                            <thead>
                            <tr>
                                <th class="product-col">Название товара</th>
                                <th class="price-col">Цена</th>
                                <th class="qty-col">Кол-во</th>
                                <th>Итого</th>
                            </tr>
                            </thead>

                            <tbody>

                            {% for item in cart %}
                            {% with good=item.product %}

                            <tr class="product-row">
                                <td class="product-col">

                                    {% if good.images_for_goods.all %}

                                    <figure class="product-image-container">

                                        {% for photo in good.images_for_goods.all %}
                                        {% if forloop.counter == 1 %}

                                        <a href="{{ good.get_absolute_url }}">
                                            <img src="{{ photo.photo.url }}" width="150">
                                        </a>

                                        {% endif %}
                                        {% endfor %}

                                    </figure>

                                    {% else %}

                                    <figure class="product-image-container">
                                        <a href="{{ good.get_absolute_url }}">
                                            <img src="{% static 'assets/images/photo_net.jpg' %}" width="150">
                                        </a>
                                    </figure>

                                    {% endif %}

                                    <h2 class="product-title">
                                        <a href="{{ good.get_absolute_url }}">{{ good.title }}</a>
                                    </h2>

                                </td>

                                <td>{{ item.price }} руб.</td>

                                <td>
                                    <br>
                                    <br>
                                    <form action="{% url 'orders:cart_add' good.id %}" method="post">

                                        {% csrf_token %}

                                        {{ item.update_quantity_form.quantity }}
                                        {{ item.update_quantity_form.update }}

                                        <input type="submit" class="btn btn-sm btn-primary" value="Обновить">
                                    </form>
                                </td>

                                <td>{{ item.total_price }} руб.</td>

                            </tr>

                            <tr class="product-action-row">
                                <td colspan="4" class="clearfix">
                                    <div class="float-left">
                                        <a href="{% url 'orders:cart_remove' good.id %}" class="btn-move">Удалить из
                                            корзины</a>
                                    </div>

                                    <div class="float-right">
                                        <a href="{% url 'shopping' %}" title="Вернуться к покупкам"
                                           class="fa fa-shopping-cart"></a>
                                    </div>

                                </td>
                            </tr>

                            {% endwith %}
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="cart-summary">
                        <h3>Сумма Вашей покупки</h3>

                        <table class="table table-totals">
                            <tbody>
                            <tr>
                                <td>{{ cart.get_total_price }} руб.</td>
                            </tr>
                            </tbody>
                            <tfoot>
                            <tr>

                            </tr>
                            </tfoot>
                        </table>

                        {% if request.user.is_authenticated %}

                        <form action="{% url 'orders:order_add' %}" method="get">

                            <div class="checkout-methods">
                                <input type="submit" class="btn btn-block btn-sm btn-primary" value="Перейти к покупке">
                            </div>

                        </form>

                        {% else %}

                        <div class="checkout-methods">
                            <p>Чтобы перейти к покупке</p>
                            <p>выбранных Вами товаров:</p>
                            <a href="{% url 'login' %}?next={{ request.path|urlencode }}">Войти</a> |
                            <a href="{% url 'register' %}">Зарегистрироваться</a>
                        </div>

                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

{% endblock %}

shop/orders/templates/orders/order.html
{% extends 'base.html' %}}
{% load static %}
{% load bootstrap4 %}


{% block title %}

Оформление заказа  :: {{ block.super }}

{% endblock %}

{% block content %}


<div class="page-wrapper">
    <main class="main">
        <nav aria-label="breadcrumb" class="breadcrumb-nav">
            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}"><i class="icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="{% url 'shopping' %}">Магазин</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'orders:orders_index' %}">Корзина</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Оформление заказа</li>
                </ol>
            </div>
        </nav>

        <div class="container mb-6">

            <div class="row">
                <div class="col-lg-8">
                    <ul class="checkout-steps">
                        <li>
                            <h2 class="step-title">Адрес доставки заказа</h2>

                            <form action="." method="post">

                                {% csrf_token %}

                                {% bootstrap_form_errors form type='fields' %}
                                {% bootstrap_form form layout='inline' %}

                                <button type="submit" class="btn btn-primary btn-block">Оформить заказ</button>
                            </form>

                        </li>
                    </ul>
                </div>

                <div class="col-lg-4">
                    <div class="order-summary">
                        <h3>Информация о покупке</h3>

                        <h4>
                            <a data-toggle="collapse" href="#order-cart-section" class="collapsed" role="button"
                               aria-expanded="false" aria-controls="order-cart-section">
                                {{ cart|length }} товара(ов) в корзине</a>
                        </h4>

                        <div class="collapse" id="order-cart-section">
                            <table class="table table-mini-cart">
                                <tbody>

                                {% for item in cart %}
                                {% with good=item.product %}

                                <tr>
                                    <td class="product-col">
                                        <figure class="product-image-container">

                                            {% if good.images_for_goods.all %}

                                            <figure class="product-image-container">

                                                {% for photo in good.images_for_goods.all %}
                                                {% if forloop.counter == 1 %}

                                                <a href="{{ good.get_absolute_url }}">
                                                    <img src="{{ photo.photo.url }}" width="150">
                                                </a>

                                                {% endif %}
                                                {% endfor %}

                                            </figure>

                                            {% else %}

                                            <figure class="product-image-container">
                                                <a href="{% url 'orders:orders_index' %}">
                                                    <img src="{% static 'assets/images/photo_net.jpg' %}" width="150">
                                                </a>
                                            </figure>

                                            {% endif %}

                                        </figure>

                                        <div>
                                            <h2 class="product-title">
                                                <a href="{% url 'orders:orders_index' %}">{{ good.title }}</a>
                                            </h2>
                                            <span class="product-qty">Количество: {{ item.quantity }}</span>
                                        </div>

                                    </td>
                                    <td class="price-col">{{ item.total_price }} руб.</td>
                                </tr>

                                {% endwith %}
                                {% endfor %}

                                <tr>
                                    <td class="product-col">
                                        <div>
                                            <h1 class="product-title">
                                                Итоговая сумма
                                            </h1>
                                        </div>
                                    </td>
                                    <td class="price-col">{{ cart.get_total_price }} руб.</td>
                                </tr>
                                </tbody>
                            </table>
							<div class="checkout-methods">
								<a href="{% url 'orders:orders_index' %}" class="btn btn-block btn-sm btn-primary">
                                    Редактировать заказ</a>
							</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

{% endblock %}

shop/orders/templates/orders/order_created.html
{% extends 'base.html' %}}
{% load static %}
{% load bootstrap4 %}

{% block title %}

Заказ оформлен  :: {{ block.super }}

{% endblock %}

{% block content %}

<main class="main">
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index' %}"><i class="icon-home"></i></a></li>
                <li class="breadcrumb-item active" aria-current="page">Заказ оформлен</li>
            </ol>
        </div>
    </nav>

    <div class="page-wrapper">
        <div class="container mb-6">

            <h2>Ваш заказ успешно оформлен.</h2>
            <p>Номер заказа: <strong>{{ order.pk }}</strong> |
                Дата: <strong>{{ order.date_at | date:"d E Y" }}</strong> |
                <strong>{{ order.get_status_display }}</strong> |
                Стоимость: <strong>{{ order.get_total_price }}</strong> руб. |
                {{ order.get_delivery_type_display }}</p>

            <p><strong>Заказанные товары:</strong></p>

            <section class="section-2 product-collection container">
                <div class="row m-0">

                    {% for item in order_items %}
                    {% with good=item.product %}

                    <div class="product-row">
                        <div class="product-col">

                            {% if good.images_for_goods.all %}

                            <figure class="product-image-container">

                                {% for photo in good.images_for_goods.all %}
                                {% if forloop.counter == 1 %}

                                <a href="{{ good.get_absolute_url }}"><img src="{{ photo.photo.url }}" width="150"></a>

                                {% endif %}
                                {% endfor %}

                            </figure>

                            {% else %}

                            <figure class="product-image-container">
                                <a href="{{ good.get_absolute_url }}">
                                    <img src="{% static 'assets/images/photo_net.jpg' %}" width="150">
                                </a>
                            </figure>

                            {% endif %}

                            <div>

                                <a href="{{ good.get_absolute_url }}"><strong>{{ good.title | truncatechars:10 }}</strong></a>

                            </div>
                        </div>

                        <div>{{ item.quantity }} х {{ item.price }} руб.<br> Всего: {{ item.get_cost }} руб.</div>

                    </div>

                    {% endwith %}
                    {% endfor %}

                </div>
            </section>
        </div>
    </div>
</main>

{% endblock %}

shop/orders/templates/orders/pay.html
{% extends 'base.html' %}}
{% load static %}
{% load bootstrap4 %}


{% block title %}
Успешная регистрация заявки  :: {{ block.super }}
{% endblock %}

{% block content %}

<div class="page-wrapper">
    <main class="main">
        <div class="container mb-6">

            <h1>Thank you</h1>
            <p>Your order has been successfully completed. Your order number is
                <strong>{{ order }}</strong>.</p>
        </div>
    </main><!-- End .main -->
</div>

{% endblock %}